services:
  web-api:
    image: web-api:e2e
    build:
      context: ../..
      dockerfile: src/Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION_STRING}
      - SQLSERVER_SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
    ports:
      - 8080:8080

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SQLSERVER_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  playwright-tests:
    build:
      context: ../e2e/gtaa.e2etests
      dockerfile: Dockerfile
    depends_on:
      - web-api
    environment:
      - API_URL=http://web-api:8080
    volumes:
      - ../e2e/gtaa.e2etests/test-results/screenshots:/tests/test-results/screenshots
    command: ["yarn", "playwright", "test", "-c", "playwright.config.ts"]
