services:
  web-api:
    image: web-api
    build:
      context: ../..
      dockerfile: src/Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - DEFAULT_CONNECTION_STRING=${DEFAULT_CONNECTION_STRING}
      - SQLSERVER_SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
    volumes:
      - ./wait-for-sqlserver.sh:/wait-for-sqlserver.sh
    entrypoint: ["/wait-for-sqlserver.sh"]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SQLSERVER_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
