services:
  web-api:
    image: web-api
    build:
      context: ../..
      dockerfile: src/Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION_STRING}
      - SQLSERVER_SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
    command: >
      /bin/sh -c '
        host="${SQLSERVER_HOST:-sqlserver}";
        port="${SQLSERVER_PORT:-1433}";
        until /opt/mssql-tools/bin/sqlcmd -S "$host,$port" -U sa -P "$SQLSERVER_SA_PASSWORD" -Q "SELECT 1" > /dev/null 2>&1; do
          echo "Waiting for SQL Server at $host:$port...";
          sleep 3;
        done;
        echo "SQL Server is up - starting app.";
        dotnet Api.dll
      '

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SQLSERVER_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5