env                 = "Dev"
product             = "Get-To-An-Answer"
prefix              = "s263d01"
location            = "uksouth"
api_image_name      = "gettoananswer-api:latest"
admin_image_name    = "gettoananswer-admin:latest"
frontend_image_name = "gettoananswer-frontend:latest"