env                 = "Dev"
asp_env             = "Development"
product             = "Get-To-An-Answer"
prefix              = "s263d01"
location            = "uksouth"
api_image_name      = "gtaa-api:latest"
admin_image_name    = "gtaa-admin:latest"
frontend_image_name = "gtaa-frontend:latest"