env                 = "Test"
asp_env             = "Test"
product             = "Get-To-An-Answer"
prefix              = "s263t01"
location            = "uksouth"
api_image_name      = "gtaa-api"
admin_image_name    = "gtaa-admin"
frontend_image_name = "gtaa-frontend"